use std::sync::Arc;
use tokio::sync::Notify;
use tokio::time::{sleep, Duration};
use tracing::{debug, error, info, warn};

use crate::auth::AuthState;
use crate::config::AppConfig;

// Event names as generated by createEvents() in events.types.ts (lowercased).
// CLOUD_FILE.CREATED → "cloud_file.created", etc.
const EV_CREATED: &str = "cloud_file.created";
const EV_UPDATED: &str = "cloud_file.updated";
const EV_DELETED: &str = "cloud_file.deleted";

/// Extract the file name from a cloud_file.* payload for logging.
/// Returns None if the payload structure is not as expected.
fn extract_file_name(payload: &rust_socketio::Payload) -> Option<String> {
    let rust_socketio::Payload::Text(values) = payload else {
        return None;
    };
    let val = values.first()?;
    let file = val.get("file")?;
    let name = file.get("name")?.as_str()?.to_string();
    Some(name)
}


/// WebSocket client that listens for CLOUD_FILE events on the /notifications namespace
/// and wakes the sync engine only when the affected folder is selected for sync.
pub struct WsClient;

impl WsClient {
    /// Runs forever — connects, listens, and auto-reconnects on failure.
    pub async fn run(config: AppConfig, _auth: AuthState, sync_trigger: Arc<Notify>) {
        loop {
            match Self::connect_once(&config, sync_trigger.clone()).await {
                Ok(()) => warn!("WS: disconnected, reconnecting in 10s…"),
                Err(e) => warn!("WS: connection failed: {e}, retrying in 10s…"),
            }
            sleep(Duration::from_secs(10)).await;
        }
    }

    async fn connect_once(config: &AppConfig, sync_trigger: Arc<Notify>) -> anyhow::Result<()> {
        // Engine.IO handshake must go to the base URL (/socket.io/).
        // The namespace is passed separately so rust_socketio doesn't
        // append "/notifications/socket.io/" instead of "/socket.io/".
        let url = &config.websocket_url;
        info!("WS: connecting to {url} (namespace /notifications)");

        // Signalled by the "disconnect" handler so the keep-alive loop can exit
        // and the outer run() loop can reconnect immediately.
        let disconnect_flag = Arc::new(Notify::new());

        let t1 = sync_trigger.clone();
        let t2 = sync_trigger.clone();
        let t3 = sync_trigger.clone();
        let df = disconnect_flag.clone();

        let _socket = rust_socketio::asynchronous::ClientBuilder::new(url)
            .namespace("/notifications")
            .on(EV_CREATED, move |payload, _| {
                let t = t1.clone();
                Box::pin(async move {
                    // Just log and trigger — the engine decides what to download
                    // based on selected folders. Notifications fire only after an
                    // actual download so the user never sees false positives.
                    if let Some(name) = extract_file_name(&payload) {
                        info!("WS: cloud_file.created ({name}) — triggering sync");
                    } else {
                        info!("WS: cloud_file.created — triggering sync");
                    }
                    t.notify_one();
                })
            })
            .on(EV_UPDATED, move |payload, _| {
                let t = t2.clone();
                Box::pin(async move {
                    info!("WS: cloud_file.updated — triggering sync");
                    let _ = payload; // event received, no filtering needed
                    t.notify_one();
                })
            })
            .on(EV_DELETED, move |payload, _| {
                let t = t3.clone();
                Box::pin(async move {
                    info!("WS: cloud_file.deleted — triggering sync");
                    let _ = payload;
                    t.notify_one();
                })
            })
            .on("disconnect", move |_, _| {
                let df = df.clone();
                Box::pin(async move {
                    warn!("WS: server disconnected — will reconnect");
                    df.notify_one();
                })
            })
            .on("error", |err, _| {
                Box::pin(async move {
                    error!("WS error: {:?}", err);
                })
            })
            .connect()
            .await
            .map_err(|e| anyhow::anyhow!("{e}"))?;

        info!("WS: connected — listening for cloud_file events");

        // Keep the socket alive until the server disconnects us.
        // When disconnect fires, exit so the outer run() loop reconnects.
        loop {
            tokio::select! {
                _ = disconnect_flag.notified() => {
                    // Connection dropped — return Ok so run() retries in 10s.
                    return Ok(());
                }
                _ = sleep(Duration::from_secs(30)) => {
                    // Still alive — keep looping.
                    debug!("WS: keep-alive tick");
                }
            }
        }
    }
}


#[cfg(test)]
#[path = "events_tests.rs"]
mod events_tests;
