use std::sync::Arc;
use std::sync::mpsc;
use tokio::sync::Notify;
use tokio::time::{sleep, Duration};
use tracing::{debug, error, info, warn};

use crate::auth::AuthState;
use crate::config::AppConfig;
use crate::update::UpdateInfo;

// Event names as generated by createEvents() in events.types.ts (lowercased).
// CLOUD_FILE.CREATED → "cloud_file.created", etc.
const EV_CREATED:    &str = "cloud_file.created";
const EV_UPDATED:    &str = "cloud_file.updated";
const EV_DELETED:    &str = "cloud_file.deleted";
const EV_CS_CHANGED: &str = "company_supervisor.changed";
/// Emitted by the backend when a new installer is published.
/// Payload: { "version": "x.y.z", "downloadUrl": "https://..." }
/// Backend event name confirmed when the endpoint is implemented — update here if needed.
const EV_APP_UPDATE: &str = "app_distribution.version_published";

// ── Tree patch (company assignment delta) ────────────────────────────────────

/// Action received from the backend when a company is assigned/unassigned.
#[derive(Debug, Clone)]
pub enum TreePatchAction {
    Added,
    Removed,
}

/// Delta update for the folder tree — sent from WsClient to FolderTreeWidget
/// via an `mpsc::channel` when the user's company assignments change.
#[derive(Debug, Clone)]
pub struct TreePatch {
    pub action:       TreePatchAction,
    /// Company UUID from the backend event. Used in tests and kept for future filtering.
    #[allow(dead_code)]
    pub company_uuid: String,
    pub company_name: String,
}

/// Extract the file name from a cloud_file.* payload for logging.
/// Returns None if the payload structure is not as expected.
fn extract_file_name(payload: &rust_socketio::Payload) -> Option<String> {
    let rust_socketio::Payload::Text(values) = payload else { return None };
    let val = values.first()?;
    let file = val.get("file")?;
    Some(file.get("name")?.as_str()?.to_string())
}

/// Extract a [`TreePatch`] from a `company_supervisor.changed` payload.
/// Returns `None` if the event is for a different user (`username` mismatch).
fn extract_tree_patch(payload: &rust_socketio::Payload, my_username: &str) -> Option<TreePatch> {
    let rust_socketio::Payload::Text(values) = payload else { return None };
    let val = values.first()?;
    // Filter: only process events addressed to this user.
    let username = val.get("username")?.as_str()?;
    if username != my_username { return None; }
    let action_str = val.get("action")?.as_str()?;
    let action = match action_str {
        "added"   => TreePatchAction::Added,
        "removed" => TreePatchAction::Removed,
        _         => return None,
    };
    let company_uuid = val.get("companyUuid")?.as_str()?.to_string();
    let company_name = val.get("companyName").and_then(|v| v.as_str()).unwrap_or("").to_string();
    Some(TreePatch { action, company_uuid, company_name })
}


/// WebSocket client that listens for CLOUD_FILE events on the /notifications namespace
/// and wakes the sync engine only when the affected folder is selected for sync.
///
/// Optionally accepts a `tree_patch_tx` channel sender + the owner's username:
/// when set, `company_supervisor.changed` events targeting that username are
/// forwarded as [`TreePatch`] deltas so the Folder Manager can update in real-time.
pub struct WsClient;

impl WsClient {
    /// Runs forever — connects, listens, and auto-reconnects on failure.
    ///
    /// `tree_patch`: pass `Some((username, sender))` from the Folder Manager subprocess
    /// to receive company-assignment delta updates. Pass `None` from the tray process.
    ///
    /// `update_tx`: pass `Some(sender)` from the tray process to receive
    /// `app.update_available` events. Pass `None` from UI subprocesses.
    pub async fn run(
        config: AppConfig,
        _auth: AuthState,
        sync_trigger: Arc<Notify>,
        tree_patch: Option<(String, mpsc::Sender<TreePatch>)>,
        update_tx: Option<mpsc::Sender<UpdateInfo>>,
    ) {
        loop {
            match Self::connect_once(
                &config,
                sync_trigger.clone(),
                tree_patch.clone(),
                update_tx.clone(),
            )
            .await
            {
                Ok(()) => warn!("WS: disconnected, reconnecting in 10s…"),
                Err(e) => warn!("WS: connection failed: {e}, retrying in 10s…"),
            }
            sleep(Duration::from_secs(10)).await;
        }
    }

    async fn connect_once(
        config: &AppConfig,
        sync_trigger: Arc<Notify>,
        tree_patch: Option<(String, mpsc::Sender<TreePatch>)>,
        update_tx: Option<mpsc::Sender<UpdateInfo>>,
    ) -> anyhow::Result<()> {
        // Engine.IO handshake must go to the base URL (/socket.io/).
        // The namespace is passed separately so rust_socketio doesn't
        // append "/notifications/socket.io/" instead of "/socket.io/".
        let url = &config.websocket_url;
        info!("WS: connecting to {url} (namespace /notifications)");

        // Signalled by the "disconnect" handler so the keep-alive loop can exit
        // and the outer run() loop can reconnect immediately.
        let disconnect_flag = Arc::new(Notify::new());

        let t1 = sync_trigger.clone();
        let t2 = sync_trigger.clone();
        let t3 = sync_trigger.clone();
        let df = disconnect_flag.clone();

        // Clone tree-patch sender for the company_supervisor.changed handler.
        let patch_tx = tree_patch.clone();

        // Clone server_url so the update handler closure can own it.
        let server_url_for_update = config.server_url.clone();

        let _socket = rust_socketio::asynchronous::ClientBuilder::new(url)
            .namespace("/notifications")
            .on(EV_CREATED, move |payload, _| {
                let t = t1.clone();
                Box::pin(async move {
                    // Just log and trigger — the engine decides what to download
                    // based on selected folders. Notifications fire only after an
                    // actual download so the user never sees false positives.
                    if let Some(name) = extract_file_name(&payload) {
                        info!("WS: cloud_file.created ({name}) — triggering sync");
                    } else {
                        info!("WS: cloud_file.created — triggering sync");
                    }
                    t.notify_one();
                })
            })
            .on(EV_UPDATED, move |payload, _| {
                let t = t2.clone();
                Box::pin(async move {
                    info!("WS: cloud_file.updated — triggering sync");
                    let _ = payload; // event received, no filtering needed
                    t.notify_one();
                })
            })
            .on(EV_DELETED, move |payload, _| {
                let t = t3.clone();
                Box::pin(async move {
                    info!("WS: cloud_file.deleted — triggering sync");
                    let _ = payload;
                    t.notify_one();
                })
            })
            .on(EV_CS_CHANGED, move |payload, _| {
                let patch_tx = patch_tx.clone();
                Box::pin(async move {
                    let Some((my_user, tx)) = patch_tx else { return };
                    let Some(patch) = extract_tree_patch(&payload, &my_user) else { return };
                    info!("WS: company_supervisor.changed ({:?}) — updating folder tree", patch.action);
                    let _ = tx.send(patch);
                })
            })
            .on(EV_APP_UPDATE, move |payload, _| {
                let tx = update_tx.clone();
                let server_url = server_url_for_update.clone();
                Box::pin(async move {
                    let Some(tx) = tx else { return };
                    // Payload: { appId, appName, version, channel, versionId, isMandatory }
                    let rust_socketio::Payload::Text(values) = payload else { return };
                    let Some(val) = values.first() else { return };

                    // Only process events for this app.
                    let app_name = val.get("appName").and_then(|v| v.as_str()).unwrap_or("");
                    if app_name != "AGBCloudClient" { return; }

                    let version = val.get("version").and_then(|v| v.as_str()).unwrap_or("").to_string();
                    let version_id = val.get("versionId").and_then(|v| v.as_u64()).unwrap_or(0);
                    let is_mandatory = val.get("isMandatory").and_then(|v| v.as_bool()).unwrap_or(false);

                    if version.is_empty() || version_id == 0 {
                        warn!("WS: app.distribution.version_published — missing version or versionId");
                        return;
                    }

                    if !crate::update::is_newer_version(&version) {
                        info!("WS: version_published for {version} — already up to date, ignoring");
                        return;
                    }

                    // Construct absolute download URL from server_url + versionId.
                    let download_url = format!(
                        "{}/app-distribution/versions/{}/download",
                        server_url, version_id
                    );
                    info!(
                        "WS: app.distribution.version_published — version {version} \
                         mandatory={is_mandatory}"
                    );
                    let _ = tx.send(UpdateInfo { version, download_url, is_mandatory });
                })
            })
            .on("disconnect", move |_, _| {
                let df = df.clone();
                Box::pin(async move {
                    warn!("WS: server disconnected — will reconnect");
                    df.notify_one();
                })
            })
            .on("error", |err, _| {
                Box::pin(async move {
                    error!("WS error: {:?}", err);
                })
            })
            .connect()
            .await
            .map_err(|e| anyhow::anyhow!("{e}"))?;

        info!("WS: connected — listening for cloud_file events");

        // Keep the socket alive until the server disconnects us.
        // When disconnect fires, exit so the outer run() loop reconnects.
        loop {
            tokio::select! {
                _ = disconnect_flag.notified() => {
                    // Connection dropped — return Ok so run() retries in 10s.
                    return Ok(());
                }
                _ = sleep(Duration::from_secs(30)) => {
                    // Still alive — keep looping.
                    debug!("WS: keep-alive tick");
                }
            }
        }
    }
}


#[cfg(test)]
#[path = "events_tests.rs"]
mod events_tests;
